name: Build for Windows ARM64

on:
  push:

jobs:
  build-windows-arm64:
    name: Build
    runs-on: windows-latest
    env:
      txs_version: "4.8.5"
      poppler_path: "${{ github.workspace }}/../poppler-msvc-arm64"
      poppler_data_version: "0.4.12"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup devcmd
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64_arm64

      - name: Install build tools
        run: |
          choco install ninja pkgconfiglite

      - name: Build TexTablet
        run: |
          git clone https://github.com/stevenlovegrove/TexTablet.git
          cd TexTablet
          git apply ../textable-vs2022-dotnet48.patch
          MSBuild /property:Configuration=Release /property:Platform=ARM64

      - name: Fetch texstudio sources
        run: |
          git clone --branch ${{ env.txs_version }} --depth 1 https://github.com/texstudio-org/texstudio.git
          cp ${{ github.workspace }}/vcpkg.json texstudio
          cd texstudio
          git apply ../fix-attribute-format-printf.patch
          $cmakelist = Get-Content "CMakeLists.txt"
          $cmakelist | Select-String -Pattern 'Wno-deprecated-declarations' -NotMatch | Set-Content "CMakeLists.txt"

      - uses: johnwason/vcpkg-action@v6
        id: vcpkg
        with:
          # The vcpkg target triplet to use. This must be set. For windows, 
          # x64-windows-release is recommended if you don't need debug libraries
          triplet: 'arm64-windows-release'
          # Extra arguments to pass to vcpkg command (optional)
          extra-args: '--clean-after-build --host-triplet=x64-windows-release --overlay-triplets=${{ github.workspace }} --x-buildtrees-root=d:/vcpkg/b' 
          # Additional string to add to cache key. If using a build matrix or building different configurations
          # on the same operating system, be sure to include an additional cache key to separate the caches. (optional)
          cache-key: 'poppler-qt6-windows-arm64'
          # vcpkg revision to checkout
          # A valid git ref; if empty, it defaults to the latest vcpkg stable release.
          revision: 'b322364f06308bdd24823f9d8f03fe0cc86fd46f'
          # GitHub token to authenticate API requests. This is necessary to determine vcpkg version to checkout
          # Recommended to use ${{ github.token }}
          token: '${{ github.token }}'
          # Directory containing vcpkg.json manifest file. Cannot be used with pkgs.
          manifest-dir: '${{ github.workspace }}/texstudio'
          # "Use vcpkg built-in GitHub binary caching if "true". If not specified, will use the dry-run based file cache."
          # Recommended set to "true"
          github-binarycache: 'true'
          #Fetch depth for vcpkg checkout. Defaults to "1"
          fetch-depth: '1'

      - name: Build TeXstudio
        run: |   
          cd texstudio 
          cmake -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}\vcpkg\scripts\buildsystems\vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=arm64-windows-release -DVCPKG_MANIFEST_MODE=ON -DVCPKG_INSTALL_OPTIONS="--clean-after-build;--host-triplet=x64-windows-release;--overlay-triplets=${{ github.workspace }}"
          cmake --build build

      - name: Install poppler-data
        run: |
          aria2c https://poppler.freedesktop.org/poppler-data-${{ env.poppler_data_version }}.tar.gz
          tar -xf poppler-data-${{ env.poppler_data_version }}.tar.gz
          cd poppler-data-${{ env.poppler_data_version }}
          cmake -G "Ninja" -DCMAKE_INSTALL_PREFIX=${{ env.poppler_path }} -DCMAKE_BUILD_TYPE=Release 
          cmake --build .
          cmake --install .

      - name: Prepare build artifacts
        run: |
          mkdir upload
          mkdir upload/config
          mkdir upload/share
          mkdir upload/TexTablet
          copy texstudio/build/texstudio.exe upload
          copy -r texstudio/utilities/dictionaries upload
          copy -r texstudio/utilities/manual upload/help
          copy texstudio/utilities/latex2e.css upload/help
          copy texstudio/utilities/latex2e.html upload/help
          copy -r texstudio/utilities/fonts upload/share
          copy -r ${{ env.poppler_path }}/share/poppler upload/share
          copy -r texstudio/templates upload
          copy -r texstudio/translation upload/translations
          copy texstudio/utilities/TexTablet/license.txt upload/TexTablet
          copy texstudio/utilities/TexTablet/*.xsl upload/TexTablet
          copy TexTablet/LatexTablet.net/bin/ARM64/Release/Interop.micautLib.dll upload/TexTablet
          copy TexTablet/LatexTablet.net/bin/ARM64/Release/TeXTablet.exe upload/TexTablet

      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: p7zip mingw-w64-ucrt-x86_64-ntldd

      - name: copy dlls in MSYS2
        shell: msys2 {0}
        run: |
          package_dir=$PWD/vcpkg/installed/arm64-windows-release
          PATH=$PATH:$package_dir/bin
          cd upload
          ntldd -R texstudio.exe | awk '{print $3}'| grep vcpkg  | sed 's|\\|/|g' | xargs -I{} cp -u {} .
          mkdir tls
          mkdir styles
          mkdir platforms
          mkdir imageformats
          mkdir iconengines
          cp $package_dir/Qt6/plugins/tls/*.dll tls
          cp $package_dir/Qt6/plugins/styles/qmodernwindowsstyle.dll styles
          cp $package_dir/Qt6/plugins/platforms/qwindows.dll platforms
          cp $package_dir/Qt6/plugins/imageformats/*.dll imageformats
          cp $package_dir/Qt6/plugins/iconengines/*.dll iconengines
          7z a -mx9 texstudio_${{ env.txs_version }}_arm64.7z *
          mv texstudio_${{ env.txs_version }}_arm64.7z ..

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: texstudio_${{ env.txs_version }}_arm64
          path: upload

      - name: Batch release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: texstudio_${{ env.txs_version }}_arm64.7z     
