name: Build for Windows ARM64

on:
  push:

jobs:
  build-windows-arm64:
    name: Build
    runs-on: windows-latest
    env:
      txs_version: "4.8.7"
      poppler_path: "${{ github.workspace }}/../poppler-msvc-arm64"
      poppler_data_version: "0.4.12"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup devcmd
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64_arm64

      - name: Install build tools
        run: |
          choco install ninja pkgconfiglite

      - name: Build TexTablet
        run: |
          git clone https://github.com/stevenlovegrove/TexTablet.git
          cd TexTablet
          git apply ../textable-vs2022-dotnet48.patch
          MSBuild /property:Configuration=Release /property:Platform=ARM64

      - name: Setup a new (or from cache) vcpkg (and does not build any package)
        uses: lukka/run-vcpkg@v11 # Always specify the specific _version_ of the
                                  # action you need, `v11` in this case to stay up
                                  # to date with fixes on the v11 branch
        with:
          vcpkgGitCommitId: 'ce613c41372b23b1f51333815feb3edd87ef8a8b'

      - name: Build TeXstudio
        run: |   
          git clone --branch ${{ env.txs_version }} --depth 1 https://github.com/texstudio-org/texstudio.git
          cp ${{ github.workspace }}/vcpkg.json texstudio
          cd texstudio
          git apply ../fix-attribute-format-printf.patch
          $cmakelist = Get-Content "CMakeLists.txt"
          $cmakelist | Select-String -Pattern 'Wno-deprecated-declarations' -NotMatch | Set-Content "CMakeLists.txt"
          cmake -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="${{ env.RUNVCPKG_VCPKG_ROOT }}\scripts\buildsystems\vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=arm64-windows-release -DVCPKG_MANIFEST_MODE=ON -DVCPKG_INSTALL_OPTIONS="--clean-after-build;--host-triplet=x64-windows-release;--overlay-triplets=${{ github.workspace }};--x-buildtrees-root=d:/vcpkg/b"
          cmake --build build

      - name: Install poppler-data
        run: |
          aria2c https://poppler.freedesktop.org/poppler-data-${{ env.poppler_data_version }}.tar.gz
          tar -xf poppler-data-${{ env.poppler_data_version }}.tar.gz
          cd poppler-data-${{ env.poppler_data_version }}
          cmake -G "Ninja" -DCMAKE_INSTALL_PREFIX=${{ env.poppler_path }} -DCMAKE_BUILD_TYPE=Release 
          cmake --build .
          cmake --install .

      - name: Prepare build artifacts
        run: |
          mkdir upload
          mkdir upload/config
          mkdir upload/share
          mkdir upload/TexTablet
          copy texstudio/build/texstudio.exe upload
          copy -r texstudio/utilities/dictionaries upload
          copy -r texstudio/utilities/manual upload/help
          copy texstudio/utilities/latex2e.css upload/help
          copy texstudio/utilities/latex2e.html upload/help
          copy -r texstudio/utilities/fonts upload/share
          copy -r ${{ env.poppler_path }}/share/poppler upload/share
          copy -r texstudio/templates upload
          copy -r texstudio/translation upload/translations
          copy texstudio/utilities/TexTablet/license.txt upload/TexTablet
          copy texstudio/utilities/TexTablet/*.xsl upload/TexTablet
          copy TexTablet/LatexTablet.net/bin/ARM64/Release/Interop.micautLib.dll upload/TexTablet
          copy TexTablet/LatexTablet.net/bin/ARM64/Release/TeXTablet.exe upload/TexTablet

      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: p7zip mingw-w64-ucrt-x86_64-ntldd

      - name: copy dlls in MSYS2
        shell: msys2 {0}
        run: |
          package_dir=$PWD/texstudio/vcpkg/installed/arm64-windows-release
          cd upload
          ntldd -R --search-dir $package_dir/bin texstudio.exe | awk '{print $3}'| grep vcpkg  | sed 's|\\|/|g' | xargs -I{} cp -u {} .
          mkdir tls
          mkdir styles
          mkdir platforms
          mkdir imageformats
          mkdir iconengines
          cp $package_dir/Qt6/plugins/tls/*.dll tls
          cp $package_dir/Qt6/plugins/styles/qmodernwindowsstyle.dll styles
          cp $package_dir/Qt6/plugins/platforms/qwindows.dll platforms
          cp $package_dir/Qt6/plugins/imageformats/*.dll imageformats
          cp $package_dir/Qt6/plugins/iconengines/*.dll iconengines
          7z a -mx9 texstudio_${{ env.txs_version }}_arm64.7z *
          mv texstudio_${{ env.txs_version }}_arm64.7z ..

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: texstudio_${{ env.txs_version }}_arm64
          path: upload

      - name: Batch release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: texstudio_${{ env.txs_version }}_arm64.7z     
